import crypto from 'node:crypto';
const id=p=>`${p}_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`;
const initial={version:1,mode:'GUARDED_AUTONOMY',execution:'READ_VERIFY_ONLY',paused:false,opportunities:[],pending:[],verified:[],costs:[],audit:[]};
export class Governor{
  constructor(store){this.store=store;this.policy={maxSingleSettlementEUR:Number(process.env.NEON_MAX_SINGLE_SETTLEMENT_EUR||1000),maxDailyVerifiedRevenueEUR:Number(process.env.NEON_MAX_DAILY_VERIFIED_REVENUE_EUR||10000),allowSpending:false,allowSigning:false,allowWithdrawals:false};this.state=structuredClone(initial);}
  async init(){this.state={...structuredClone(initial),...(await this.store.init(initial))};this.audit('INIT',{});await this.save();}
  audit(type,data){this.state.audit.push({id:id('audit'),at:new Date().toISOString(),type,data});this.state.audit=this.state.audit.slice(-500);}
  async save(){await this.store.write(this.state);}
  status(){const revenue=this.state.verified.reduce((a,x)=>a+x.amountEUR,0);const costs=this.state.costs.filter(x=>x.status==='VERIFIED').reduce((a,x)=>a+x.amountEUR,0);return {mode:this.state.mode,execution:this.state.execution,paused:this.state.paused,policy:this.policy,metrics:{verifiedRevenueEUR:revenue,verifiedCostsEUR:costs,netVerifiedEUR:revenue-costs,pending:this.state.pending.length,verified:this.state.verified.length},lastAudit:this.state.audit.at(-1)||null};}
  async pause(reason='operator'){this.state.paused=true;this.audit('PAUSE',{reason});await this.save();return this.status();}
  async resume(reason='operator'){this.state.paused=false;this.audit('RESUME',{reason});await this.save();return this.status();}
  async pending({provider,providerRef,amountEUR,metadata={}}){if(this.state.paused)throw Error('AUTONOMY_PAUSED');if(!provider||!providerRef)throw Error('PROVIDER_REFERENCE_REQUIRED');const a=Number(amountEUR);if(!(a>0)||a>this.policy.maxSingleSettlementEUR)throw Error('SETTLEMENT_LIMIT');const dup=this.state.pending.find(x=>x.provider===provider&&x.providerRef===providerRef)||this.state.verified.find(x=>x.provider===provider&&x.providerRef===providerRef);if(dup)return dup;const x={id:id('settle'),provider,providerRef,amountEUR:a,status:'PENDING_VERIFICATION',createdAt:new Date().toISOString(),metadata};this.state.pending.push(x);this.audit('PENDING',{id:x.id,provider,amountEUR:a});await this.save();return x;}
  async verify({settlementId,provider,providerRef,amountEUR,verification}){if(this.state.paused)throw Error('AUTONOMY_PAUSED');const p=this.state.pending.find(x=>x.id===settlementId);if(!p)throw Error('PENDING_NOT_FOUND');const a=Number(amountEUR);if(p.provider!==provider||p.amountEUR!==a||p.providerRef!==providerRef)throw Error('SETTLEMENT_MISMATCH');if(verification?.verified!==true)throw Error('TRUSTED_VERIFICATION_REQUIRED');const day=new Date().toISOString().slice(0,10);const daily=this.state.verified.filter(x=>x.verifiedAt.startsWith(day)).reduce((s,x)=>s+x.amountEUR,0);if(daily+a>this.policy.maxDailyVerifiedRevenueEUR)throw Error('DAILY_LIMIT');const v={...p,status:'VERIFIED',verifiedAt:new Date().toISOString(),verification};this.state.pending=this.state.pending.filter(x=>x.id!==p.id);this.state.verified.push(v);this.audit('REVENUE_VERIFIED',{id:v.id,provider,amountEUR:a});await this.save();return v;}
}
